[package]
name = "compiler"
version = "0.0.0"
edition = "2021"
license = "CC0-1.0"
description = "compiler"

[dependencies]
anyhow = "1.0.66"
boilerplate = "0.2.2"
clap = { version = "4.0.29", features = ["derive"] }
html-escaper = "0.2.0"
image = "0.24.5"
rand = "0.8.5"
